spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${RANKIT_MAIL}
    password: ${RANKIT_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true