name: rankit-multiaz-rolling-zerodowntime-cicd

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. AWS CLI 설치
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      # 2. AWS 자격 증명 설정
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-northeast-2  # 서울 AWS 리전을 설정

      # 3. ALB 연결 끊기 (EC2-A)
      - name: Deregister EC2-A from Target Group
        run: |
          aws elbv2 deregister-targets \
            --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
            --targets Id=${{ secrets.EC2_A_ID }}
          echo "EC2-A has been deregistered from the ALB."

      # 4. Bastion 호스트에 접속하여 EC2-A에 docker-compose 실행
      - name: Deploy to EC2-A via Bastion Host
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.API_RANKIT_PEM }}  # SSH 개인 키
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$BASTION_HOST << 'EOF'
            ssh -o StrictHostKeyChecking=no -i /home/ec2-user/my-key.pem ec2-user@${{ secrets.EC2_A_IP }} << 'INNER_EOF'
              if [ $(docker-compose ps -q app | xargs -r docker inspect -f '{{.State.Running}}') == 'true' ]; then
                docker-compose stop;
              fi
              sleep 3
              docker-compose up -d --pull always

              # 헬스 체크
              sleep 5  # 컨테이너가 시작될 시간을 주기 위해 잠시 대기
              if curl -s 127.0.0.1:8080 | grep -q "health Check Success"; then
                echo "EC2-A is healthy."
              else
                echo "EC2-A health check failed."
                exit 1  # 파이프라인 종료
              fi
            INNER_EOF
          EOF
          rm private_key.pem  # 사용 후 PEM 파일 삭제

      # 5. ALB 연결 복원 (EC2-A)
      - name: Register EC2-A back to Target Group
        run: |
          aws elbv2 register-targets \
            --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
            --targets Id=${{ secrets.EC2_A_ID }}
          echo "EC2-A has been registered back to the ALB."

      # 6. ALB 연결 상태 확인 (EC2-A)
      - name: Check Health of ALB Connection to EC2-A
        run: |
          MAX_ATTEMPTS=30
          ATTEMPT=0
      
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
              --query "TargetHealthDescriptions[?Target.Id=='${{ secrets.EC2_A_ID }}'].TargetHealth.State" \
              --output text)
      
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "EC2-A is healthy in ALB."
              break
            else
              echo "Waiting for EC2-A to become healthy in ALB..."
              sleep 10  # 10초 대기 후 상태 확인
              ATTEMPT=$((ATTEMPT + 1))  # 시도 횟수 증가
            fi
      
            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
              echo "EC2-A is not healthy in ALB after $MAX_ATTEMPTS attempts. Exiting."
              exit 1  # 파이프라인 종료
            fi
          done

      # 7. ALB 연결 끊기 (EC2-C)
      - name: Deregister EC2-C from Target Group
        run: |
          aws elbv2 deregister-targets \
            --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
            --targets Id=${{ secrets.EC2_C_ID }}
          echo "EC2-C has been deregistered from the ALB."

      # 8. Bastion 호스트에 접속하여 EC2-C에 docker-compose 실행
      - name: Deploy to EC2-C via Bastion Host
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.API_RANKIT_PEM }}  # SSH 개인 키
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$BASTION_HOST << 'EOF'
            ssh -o StrictHostKeyChecking=no -i /home/ec2-user/my-key.pem ec2-user@${{ secrets.EC2_C_IP }} << 'INNER_EOF'
              if [ $(docker-compose ps -q app | xargs -r docker inspect -f '{{.State.Running}}') == 'true' ]; then
                docker-compose stop;
              fi
              sleep 3
              docker-compose up -d --pull always

              # 헬스 체크
              sleep 5  # 컨테이너가 시작될 시간을 주기 위해 잠시 대기
              if curl -s 127.0.0.1:8080 | grep -q "health Check Success"; then
                echo "EC2-C is healthy."
              else
                echo "EC2-C health check failed."
                exit 1  # 파이프라인 종료
              fi
            INNER_EOF
          EOF
          rm private_key.pem  # 사용 후 PEM 파일 삭제

      # 9. ALB 연결 복원 (EC2-C)
      - name: Register EC2-C back to Target Group
        run: |
          aws elbv2 register-targets \
            --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
            --targets Id=${{ secrets.EC2_C_ID }}
          echo "EC2-C has been registered back to the ALB."

      # 10. ALB 연결 상태 확인 (EC2-C)
      - name: Check Health of ALB Connection to EC2-C
        run: |
          MAX_ATTEMPTS=30
          ATTEMPT=0
      
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
              --query "TargetHealthDescriptions[?Target.Id=='${{ secrets.EC2_C_ID }}'].TargetHealth.State" \
              --output text)
      
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "EC2-C is healthy in ALB."
              break
            else
              echo "Waiting for EC2-C to become healthy in ALB..."
              sleep 10  # 10초 대기 후 상태 확인
              ATTEMPT=$((ATTEMPT + 1))  # 시도 횟수 증가
            fi
      
            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
              echo "EC2-C is not healthy in ALB after $MAX_ATTEMPTS attempts. Exiting."
              exit 1  # 파이프라인 종료
            fi
          done
