name: rankit-multiaz-rolling-zerodowntime-cicd

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ap-northeast-2
      
      - name: Deploy to EC2-A via Bastion Host
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.API_RANKIT_PEM }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          cat << 'EOSSH' > deploy.sh
          ssh -o StrictHostKeyChecking=no -i /home/ec2-user/my-key.pem ec2-user@${{ secrets.EC2_A_IP }} '
          if [ "$(docker-compose ps -q app | xargs -r docker inspect -f '\''{{.State.Running}}'\'')" = "true" ]; then
            docker-compose stop
          fi
          sleep 3 && docker-compose up -d --pull always
          '
          EOSSH
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$BASTION_HOST 'bash -s' < deploy.sh
          rm private_key.pem deploy.sh
          
      - name: Register EC2-A to Target Group
        run: |
          MAX_ATTEMPTS=30
          ATTEMPT=0
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
              --query "TargetHealthDescriptions[?Target.Id=='${{ secrets.EC2_A_ID }}'].TargetHealth.State" \
              --output text)
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "EC2-A is healthy."
              break
            else
              echo "Waiting for EC2-A to become healthy..."
              sleep 10
              ATTEMPT=$((ATTEMPT + 1))
            fi
            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
              echo "EC2-A is not healthy after $MAX_ATTEMPTS attempts. Exiting."
              exit 1
            fi
          done

      - name: Deploy to EC2-C via Bastion Host
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.API_RANKIT_PEM }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          cat << 'EOSSH' > deploy.sh
          ssh -o StrictHostKeyChecking=no -i /home/ec2-user/my-key.pem ec2-user@${{ secrets.EC2_C_IP }} '
          if [ "$(docker-compose ps -q app | xargs -r docker inspect -f '\''{{.State.Running}}'\'')" = "true" ]; then
            docker-compose stop
          fi
          sleep 3 && docker-compose up -d --pull always
          '
          EOSSH
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$BASTION_HOST 'bash -s' < deploy.sh
          rm private_key.pem deploy.sh

      - name: Register EC2-C to Target Group
        run: |
          MAX_ATTEMPTS=30
          ATTEMPT=0
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            HEALTH_STATUS=$(aws elbv2 describe-target-health \
              --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
              --query "TargetHealthDescriptions[?Target.Id=='${{ secrets.EC2_C_ID }}'].TargetHealth.State" \
              --output text)
            if [ "$HEALTH_STATUS" == "healthy" ]; then
              echo "EC2-C is healthy."
              break
            else
              echo "Waiting for EC2-C to become healthy..."
              sleep 10
              ATTEMPT=$((ATTEMPT + 1))
            fi
            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
              echo "EC2-C is not healthy after $MAX_ATTEMPTS attempts. Exiting."
              exit 1
            fi
          done
